### ISSUE TITLE
When using the shadow DOM, keyframes defined in <head> don't work

### ISSUE THREAD

**Issue by PSG-Luna** [parnham/css_animation.dart#5]
When trying to animate an element part of another element's shadow DOM, keyframes defined in the <head> tag won't work, they need to be defined within the shadow DOM

**Comment by parnham** [comment]
This little helper was implemented before the shadow DOM was a thing, but I'll try and take a look at how CssAnimation could deal with it.

Are you attempting to use it from a Polymer element?

**Comment by PSG-Luna** [comment]
Yes, I'm indeed trying to use this from a polymer element.

**Comment by parnham** [comment]
I've pushed a change (@28dd25f6) that should address the situation and also published a new version of the package.

I couldn't figure out how to get it to switch automatically so unfortunately it requires a minor change to how you use CssAnimation from a polymer element, when you call the `apply` function simply include the named argument `shadow` and pass it the shadow root of the component. For example:

``` dart
this.myanimation.apply($["myelement"], iterations: 2, alternate: true, duration: 500, shadow: this.shadowRoot);
```

Let me know if that helps.

**Comment by luna-duclos** [comment]
Thanks! Gonna check it now

PS: You've left sublime-workspace in version control, is that intended ?

**Comment by parnham** [comment]
I now do most of my dart and C++ dev in sublime text, so I've included a project file. It shouldn't interfere with anything hopefully.

**Comment by luna-duclos** [comment]
This seems to work at first glance :)

**Comment by parnham** [comment]
Great!
